from __future__ import annotations

from pathlib import Path

# ── Excluded binary / generated extensions ────────────────────────────────────
EXCLUDED_EXTENSIONS: frozenset[str] = frozenset({
    ".exe", ".dll", ".so", ".dylib", ".class", ".pyc", ".pyo", ".pyd",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar", ".tgz",
    ".jar", ".war", ".ear", ".whl", ".egg",
    ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico", ".webp",
    ".mp4", ".mp3", ".wav", ".avi", ".mov", ".mkv",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".map",   # source maps
    ".lock",  # lockfiles — large, low RAG value
})

# ── Excluded filenames (by exact name — not extension) ────────────────────────
# These files have normal extensions (.json, .yaml...) but are GENERATED
# automatically and contain no useful code. Indexing them pollutes results.
# Example: package-lock.json (4500+ lines) was retrieved as top result for
# "how does API key authentication work?" — consuming the whole context budget.
EXCLUDED_FILENAMES: frozenset[str] = frozenset({
    "package-lock.json",    # generated by npm  — thousands of lines, no logic
    "yarn.lock",            # generated by yarn
    "pnpm-lock.yaml",       # generated by pnpm
    "composer.lock",        # generated by PHP Composer
    "Gemfile.lock",         # generated by Ruby Bundler
    "poetry.lock",          # generated by Python Poetry
    "pipfile.lock",         # generated by Pipenv (lowercase variant)
})

# Partial suffix matches (ends-with)
EXCLUDED_SUFFIX_PATTERNS: tuple[str, ...] = (
    ".min.js",
    ".min.css",
    ".bundle.js",
    ".d.ts",   # TypeScript declaration files — no logic
)

# ── Excluded directories ──────────────────────────────────────────────────────
EXCLUDED_DIRS: frozenset[str] = frozenset({
    "node_modules", ".git", "__pycache__", "vendor",
    ".venv", "venv", ".env",
    "dist", "build", "out", "target", "bin", "obj",
    ".idea", ".vscode", ".eclipse",
    "coverage", ".nyc_output", ".pytest_cache",
    "migrations",
    "fixtures",
    "__snapshots__",
    # ── Java / Maven generated directories (spec §3.2) ─────────────────────
    ".mvn",         # Maven wrapper directory — generated, not user code
})

# ── Supported languages ───────────────────────────────────────────────────────
SUPPORTED_LANGUAGES: dict[str, str] = {
    # Python
    ".py": "python",
    # JavaScript / TypeScript
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    # Java
    ".java": "java",
    # Go
    ".go": "go",
    # Rust
    ".rs": "rust",
    # C / C++
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    # C#
    ".cs": "csharp",
    # Ruby / PHP
    ".rb": "ruby",
    ".php": "php",
    # Infrastructure
    ".tf": "terraform",
    ".hcl": "hcl",
    # Config / data
    ".yaml": "yaml",
    ".yml": "yaml",
    ".json": "json",
    ".toml": "toml",
    # Shell
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "bash",
    # SQL
    ".sql": "sql",
    # Docs
    ".md": "markdown",
    ".rst": "text",
    ".txt": "text",
    ".env.example": "text",
    ".env.sample": "text",
    # ── Angular / Spring Boot additions (spec §3.1) ────────────────────────
    ".html": "html",          # Angular templates
    ".scss": "css",           # Angular styles
    ".css": "css",            # Angular / general styles
    ".xml": "xml",            # Spring Boot pom.xml, configuration files
    ".properties": "text",    # Spring Boot application.properties
}

NAMED_FILES: dict[str, str] = {
    "Dockerfile": "dockerfile",
    "Makefile": "makefile",
    "Rakefile": "ruby",
    "Gemfile": "ruby",
    "Pipfile": "toml",
    "Cargo.toml": "toml",
    "go.mod": "go",
    "go.sum": "text",
    "pyproject.toml": "toml",
    "setup.py": "python",
    "setup.cfg": "text",
    # ── Java / Spring Boot named files (spec §3.1) ─────────────────────────
    "pom.xml": "xml",                    # Maven build file — most important Java file
    "application.properties": "text",   # Spring Boot config
    "application.yml": "yaml",          # Spring Boot config (YAML variant)
    # ── Angular named files (spec §3.1) ───────────────────────────────────
    "angular.json": "json",             # Angular workspace config
    "tsconfig.json": "json",            # TypeScript config
    "package.json": "json",             # npm project config (NOT package-lock.json)
}

MAX_FILE_SIZE_BYTES: int = 500_000  # 500 KB per spec


def should_index_file(path: Path) -> bool:
    """Return True iff this file should be indexed."""

    # ── 1. Exclude by exact filename — FIRST check, before anything else ──────
    # These files have valid extensions but contain generated/useless content
    # that pollutes RAG results (spec §3.2).
    if path.name in EXCLUDED_FILENAMES:
        return False

    # ── 2. Excluded directories in path hierarchy ─────────────────────────────
    for part in path.parts:
        if part in EXCLUDED_DIRS:
            return False

    # ── 3. Named file check (Dockerfile, pom.xml, Makefile…) ─────────────────
    if path.name in NAMED_FILES:
        return True

    # ── 4. Size check ─────────────────────────────────────────────────────────
    try:
        if path.stat().st_size > MAX_FILE_SIZE_BYTES:
            return False
    except OSError:
        return False

    # ── 5. Partial suffix patterns (.min.js etc.) ─────────────────────────────
    name_lower = path.name.lower()
    if any(name_lower.endswith(p) for p in EXCLUDED_SUFFIX_PATTERNS):
        return False

    # ── 6. Extension check ────────────────────────────────────────────────────
    suffix = path.suffix.lower()
    if not suffix:
        return False

    return suffix not in EXCLUDED_EXTENSIONS and suffix in SUPPORTED_LANGUAGES


def get_language(path: Path) -> str | None:
    """Return the language identifier for a file, or None if unsupported."""
    if path.name in NAMED_FILES:
        return NAMED_FILES[path.name]
    suffix = path.suffix.lower()
    return SUPPORTED_LANGUAGES.get(suffix)